### PR TITLE
Fix timing issue

### PR DESCRIPTION
**Pull request by blasten**
This should fix a timing issue. cc @keanulee

### CODE REVIEW

**Comment by ebidel** [comment]
:+1:

**Comment by ebidel** [comment]
We'll need this for https://github.com/GoogleChrome/ioweb2016/pull/196 to be merged

**Comment by frankiefu** [comment]
LGTM.  @blasten, can you add a test to cover this issue?

**Comment by blasten** [comment]
:+1:

**Comment by blasten** [comment]
Just fixed the test & added a mixin that is also required for IOWA.

**Comment by frankiefu** [comment]
lgtm

**Comment by ebidel** [comment]
@blasten this doesn't seem to work in polyfilled browsers

**Pull request merged**
