### PR TITLE
README: remove duplicated content.

### PR DESCRIPTION
**Pull request by ebidel**
R: @keanulee @blasten @frankiefu

### CODE REVIEW

**Comment by blasten** [comment]
Thanks!

**Comment by ebidel** [comment]
BTW. I think it's `setUp` now?

**Comment by frankiefu** [comment]
Actually `setup` is not needed for elements that consume `AppScrollEffectsBehavior`.  `setUp` is needed if you defining a custom effect object.  @emmanuel:  I think we are still missing a section on how to create a custom effect.

**Comment by blasten** [comment]
yeah

**Pull request merged**
