### PR TITLE
Set drawer visibility hidden when not shown

### PR DESCRIPTION
**Pull request by keanulee**
cc @blasten

### CODE REVIEW

**Comment by blasten** [comment]
LGTM. minor: it'd be good to test for focus, but we can do that once we implement focus management. That way, we would know that our assumptions are correct in every browser,

**Comment by blasten** [comment]
btw, this test is failing in safari:
```js
assert.notEqual(contentContainer.style.transitionTimingFunction, drawer.FLING_TIMING_FUNCTION);
```
I think we need to test `webkitTransitionTimingFunction` in safari.

**Comment by frankiefu** [comment]
@blasten, transition (without prefix) should be supported in Safari 8+

@keanulee, LGTM

**Comment by frankiefu** [comment]
Yeah we should look at why the test is failing on Safari 8.  Interestingly it passed on Safari 7 and 9.

**Comment by keanulee** [comment]
The test is just flaky on Safari - passed on my local VM and when I restarted the test.

**Pull request merged**
