### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by blasten**

### CODE REVIEW

**Comment by keanulee** [comment]
LGTM

**Comment by blasten** [comment]
Just updated the docs for app-header https://github.com/PolymerLabs/app-layout/tree/next-docs/app-header. They look much better now. PTAL

**Comment by robdodson** [comment]
do i need to import the scroll effects or do they come along for free?

**Comment by frankiefu** [comment]
Yes, in order to use the effects in `app-header` you need to import `app-scroll-effects.html`.  This is international so if users don't need to use effects in `app-header` then they don't have to import the extra code.  We will update the doc to mention this.

**Pull request merged**
