### PR TITLE
Add toolbar role to app-toolbar

### LINKED ISSUE #34: role="toolbar" in app-toolbar
How about add this as hostAttribute in app-toolbar by default?

### PR DESCRIPTION
**Pull request by diegohaz**
Fixes #34

### CODE REVIEW

**Comment by blasten** [comment]
:+1:

**Comment by keanulee** [comment]
This may not be ideal when the toolbar is empty and only used for layout. For example, https://github.com/PolymerLabs/app-layout/blob/master/app-header/demo/contacts.html. WDYT @blasten @frankiefu

**Comment by blasten** [comment]
@keanulee yes, this needs further exploration.

**Comment by frankiefu** [comment]
For now, our suggestion is that the user would need to put the `role="toolbar"` on the `<app-toolbar>` that actually contains useful elements like button or controls.

**Pull request closed without merging**
